spring:
  datasource:
    url: jdbc:postgresql://crm-db:5432/crmdb
    username: crm
    password: crm
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework: INFO